### PR TITLE
Change Structure

### PR DESCRIPTION
**Pull request by Cryptum169**

### CODE REVIEW

**Comment by Moelf** [comment]
@mattzjack

**Comment by Cryptum169** [comment]
Somewhat related to #1. Not convinced is the same thing

**Comment by mattzjack** [comment]
what do you mean not the same thing it's most certainly the same thing

**Comment by Cryptum169** [comment]
In #1 there's something related to user. Great it turned out to be the same thing.

**Comment by mattzjack** [comment]
now all the input is broken )-:

**Comment by Cryptum169** [comment]
iirc I added prefixes and at least Julia and Python still works. You can't call them from top directory tho.

**Comment by mattzjack** [comment]
nvm I see some ocaml files also updated. appreciate the effort :heart_decoration:

**Pull request merged**
