### PR TITLE
Day 15

### PR DESCRIPTION
**Pull request by Cryptum169**

### CODE REVIEW

**Comment by Moelf** [comment]
can we do something about the commit history?

**Comment by Cryptum169** [comment]
Fixing based on this https://stackoverflow.com/questions/41283955/github-keeps-saying-this-branch-is-x-commits-ahead-y-commits-behind

**Comment by Moelf** [comment]
yeah basically everytime I do
```shell
git pull origin master
git push # this goes to fork
```
and `git checkout -b new_branch` for PR, and just delete branch after. makes it easy to work on different PRs at once.

**Comment by Cryptum169** [comment]
I'm not able to do this since it's a fork, a rebase to upstream is required every time it seems.

**Comment by Cryptum169** [comment]
Oh I see, a new branch every time,

**Comment by Moelf** [comment]
yeah you push `new_branch` to `fork` and the PR is `upstream/master <- fork/new_branch`. if you use [gh](https://cli.github.com/), you simply:
```shell
git add...
git commit...
gh pr create # and hit enter 3 times or something for the prompts
```
and it will automatically submit PR from `fork/new_branch`, no need to click buttons in browser

**Pull request merged**
